services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - ./init-scripts/UrlShortener:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: Recep
      POSTGRES_PASSWORD: Password123.
      POSTGRES_DB: UrlShortener
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3.12-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.1
    environment:
      - xpack.security.enabled=false 
      - discovery.type=single-node
      - xpack.monitoring.collection.enabled=true
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - backend

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.1
    ports:
      - "5601:5601"
    networks:
      - backend
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.9.1
    user: root
    environment:
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    networks:
      - backend
    depends_on:
      - elasticsearch
    volumes:
      - esdata:/var/log/app/

  
