services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - ./init-scripts/UrlShortener:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: Recep
      POSTGRES_PASSWORD: Password123.
      POSTGRES_DB: UrlShortener
    networks:
      - backend

  mysql:
    image: mysql:8.0-debian
    ports:
      - 3306:3306
    volumes:
      - ./init-scripts/Quartz:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: Recep
      MYSQL_PASSWORD: Password123.
      MYSQL_DATABASE: Quartz
      MYSQL_RANDOM_ROOT_PASSWORD: Yes
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3.12-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - backend
