services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - ./init-scripts/UrlShortener:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: Recep
      POSTGRES_PASSWORD: Password123.
      POSTGRES_DB: UrlShortener
    networks:
      - backend

  postgres_for_expiry_checker:
    image: postgres:15
    ports:
      - 5433:5432
    volumes:
      - ./init-scripts/Quartz:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: Recep
      POSTGRES_PASSWORD: Password123.
      POSTGRES_DB: Quartz
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3.12-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - backend
