services:
  buffer_api:
    image: ${DOCKER_REGISTRY-}buffer_api
    build:
      context: .
      dockerfile: src/Buffer/WebAPI/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - backend

  shortener_api:
    image: ${DOCKER_REGISTRY-}shortener_api
    build:
      context: .
      dockerfile: src/Shortener/WebAPI/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - backend

  expiry_check_api:
    image: ${DOCKER_REGISTRY-}expiry_check_api
    build:
      context: .
      dockerfile: src/ExpiryChecker/WebAPI/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - backend

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: src/Gateway/Gateway.WebAPI/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 5043:80
    depends_on:
      - expiry_check_api
      - shortener_api
      - buffer_api
    networks:
      - backend
      - fronted

  webui:
    image: ${DOCKER_REGISTRY-}webui
    ports:
      - 8080:80
    build:
      context: src/Fronted/webui
      dockerfile: Dockerfile
    depends_on:
      - apigateway
    networks:
      - fronted

